module.exports.CREATE_USERS_TABLE = `
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  username VARCHAR (255) UNIQUE,
  firstname VARCHAR (255),
  lastname VARCHAR (255),
  email VARCHAR (255) UNIQUE,
  password VARCHAR (255),
  status  VARCHAR (10),
  block INTEGER[] DEFAULT '{}',
  friends INTEGER[] DEFAULT '{}'
  );
`;

module.exports.CREATE_MESSAGES_TABLE = `
CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  authorid INTEGER,
  title VARCHAR(255) NOT NULL,
  message VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_author FOREIGN KEY (authorid) REFERENCES users (id)
);
`;
